export const addSelectedIngredient="ADD_SELECTED_INGREDIENT"
export const removeSelectedIngredient="REMOVE_SELECTED_INGREDIENT"
export const pullIngredientList="PULL_INGREDIENT_LIST"
export const pullOrders="PULL_LATEST_ORDERS"
export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAIL="AUTH_FAIL"
export const AUTH_REGISTER="AUTH_REGISTER"
